controller.player1.onButtonEvent(ControllerButton.A, ControllerButtonEvent.Released, function () {
    projectile = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . f f f f f f f f . . . . 
        . . . f 1 f f f 1 f f f f . . . 
        . . f 1 1 1 f 1 1 1 f 1 1 f . . 
        . f 1 1 1 1 1 1 1 1 1 1 1 1 f . 
        . f 1 1 1 f 1 1 1 f 1 1 1 1 f . 
        . f f 1 f f f 1 f f f 1 1 f f . 
        . . f f f f f f f f f f f f . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, mySprite, 50, 50)
    effects.clearParticles(bad_player)
})
let bad_player: Sprite = null
let mySprite: Sprite = null
let projectile: Sprite = null
effects.clearParticles(projectile)
mySprite = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
controller.player1.moveSprite(mySprite)
forever(function () {
    for (let index = 0; index < 4; index++) {
        effects.clearParticles(projectile)
        bad_player = sprites.create(img`
            ........................
            ............cc..........
            ............ccc.........
            ........ccc.ccccccc.....
            ........ccccc555555cc...
            ........ccb5555555555c..
            .....ccc.b55555ff15555c.
            .....cccb5555555ff55555c
            ......cb555555555555d55c
            ....c.b555555555bb55555c
            ....ccb555ddd5555b13bbc.
            ....ccd55ddddd555b3335c.
            .....cdd5ddddddd55b335c.
            ...c.bddddb555bbbd555c..
            ...ccdddddbb55555bccc...
            ...ccdddddddcc555bcc....
            ...ccddddddddbcccbcccc..
            .ccbddddddd55dbbbbc55c..
            ccddddddddd555dbbcc5c...
            cddddddbbbdd555bbccc....
            .ccddddbbbbdd55bcc......
            ...cccbbbbbdddbcddcc....
            .....cccccdd555dcccc....
            ..........cccccc........
            `, SpriteKind.Enemy)
    }
    music.play(music.createSoundEffect(WaveShape.Sine, 5000, 5000, 255, 255, 600, SoundExpressionEffect.None, InterpolationCurve.Linear), music.PlaybackMode.UntilDone)
})
game.onUpdateInterval(500, function () {
    scene.setBackgroundColor(15)
})
